import {
  CAVERNAS_MBOI_ENTRANCE_PRESET_ID,
  CAVERNAS_MBOI_ENTRANCE_PROMPT,
  CAVERNAS_MBOI_ROOM1_PRESET_ID,
  CAVERNAS_MBOI_ROOM1_PROMPT,
  CAVERNAS_MBOI_ROOM2_PRESET_ID,
  CAVERNAS_MBOI_ROOM2_PROMPT,
  CAVERNAS_MBOI_ROOM3_PRESET_ID,
  CAVERNAS_MBOI_ROOM3_PROMPT,
  CAVERNAS_MBOI_ROOM4_PRESET_ID,
  CAVERNAS_MBOI_ROOM4_PROMPT,
  CAVERNAS_MBOI_ROOM5_PRESET_ID,
  CAVERNAS_MBOI_ROOM5_PROMPT,
  CAVERNAS_MBOI_ROOM6_PRESET_ID,
  CAVERNAS_MBOI_ROOM6_PROMPT,
  CAVERNAS_MBOI_ROOM7_PRESET_ID,
  CAVERNAS_MBOI_ROOM7_PROMPT,
  CAVERNAS_MBOI_ROOM8_PRESET_ID,
  CAVERNAS_MBOI_ROOM8_PROMPT,
  CAVERNAS_MBOI_ROOM9_PRESET_ID,
  CAVERNAS_MBOI_ROOM9_PROMPT,
  cavernasMboiEntranceGuardFromAtlas,
  cavernasMboiRoom1GuardFromAtlas,
  cavernasMboiRoom2GuardFromAtlas,
  cavernasMboiRoom3GuardFromAtlas,
  cavernasMboiRoom4GuardFromAtlas,
  cavernasMboiRoom5GuardFromAtlas,
  cavernasMboiRoom6GuardFromAtlas,
  cavernasMboiRoom7GuardFromAtlas,
  cavernasMboiRoom8GuardFromAtlas,
  cavernasMboiRoom9GuardFromAtlas,
} from "./cavernasMboiPresets";
import type { AraunaPresetCatalogEntry } from "./araunaPresetCatalog";

export const CAVERNAS_MBOI_CATALOG_ENTRIES: readonly AraunaPresetCatalogEntry[] = [
  { id: CAVERNAS_MBOI_ENTRANCE_PRESET_ID, label: "Cavernas M'Boi · Entrada", prompt: CAVERNAS_MBOI_ENTRANCE_PROMPT, guardFromAtlas: cavernasMboiEntranceGuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM1_PRESET_ID, label: "Cavernas M'Boi · Sala 1", prompt: CAVERNAS_MBOI_ROOM1_PROMPT, guardFromAtlas: cavernasMboiRoom1GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM2_PRESET_ID, label: "Cavernas M'Boi · Sala 2", prompt: CAVERNAS_MBOI_ROOM2_PROMPT, guardFromAtlas: cavernasMboiRoom2GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM3_PRESET_ID, label: "Cavernas M'Boi · Sala 3", prompt: CAVERNAS_MBOI_ROOM3_PROMPT, guardFromAtlas: cavernasMboiRoom3GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM4_PRESET_ID, label: "Cavernas M'Boi · Sala 4", prompt: CAVERNAS_MBOI_ROOM4_PROMPT, guardFromAtlas: cavernasMboiRoom4GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM5_PRESET_ID, label: "Cavernas M'Boi · Sala 5", prompt: CAVERNAS_MBOI_ROOM5_PROMPT, guardFromAtlas: cavernasMboiRoom5GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM6_PRESET_ID, label: "Cavernas M'Boi · Sala 6 · Correntes", prompt: CAVERNAS_MBOI_ROOM6_PROMPT, guardFromAtlas: cavernasMboiRoom6GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM7_PRESET_ID, label: "Cavernas M'Boi · Sala 7 · Correntes", prompt: CAVERNAS_MBOI_ROOM7_PROMPT, guardFromAtlas: cavernasMboiRoom7GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM8_PRESET_ID, label: "Cavernas M'Boi · Sala 8", prompt: CAVERNAS_MBOI_ROOM8_PROMPT, guardFromAtlas: cavernasMboiRoom8GuardFromAtlas },
  { id: CAVERNAS_MBOI_ROOM9_PRESET_ID, label: "Cavernas M'Boi · Núcleo", prompt: CAVERNAS_MBOI_ROOM9_PROMPT, guardFromAtlas: cavernasMboiRoom9GuardFromAtlas },
] as const;
