import {
  NAVIO_PERDIDO_CAPTAIN_PRESET_ID, NAVIO_PERDIDO_CAPTAIN_PROMPT,
  NAVIO_PERDIDO_CORRIDORS_1F_PRESET_ID, NAVIO_PERDIDO_CORRIDORS_1F_PROMPT,
  NAVIO_PERDIDO_CORRIDORS_B1F_PRESET_ID, NAVIO_PERDIDO_CORRIDORS_B1F_PROMPT,
  NAVIO_PERDIDO_DECK_PRESET_ID, NAVIO_PERDIDO_DECK_PROMPT,
  NAVIO_PERDIDO_HIDDEN_CORRIDORS_PRESET_ID, NAVIO_PERDIDO_HIDDEN_CORRIDORS_PROMPT,
  NAVIO_PERDIDO_HIDDEN_ROOMS_PRESET_ID, NAVIO_PERDIDO_HIDDEN_ROOMS_PROMPT,
  NAVIO_PERDIDO_ROOM_B1F_PRESET_ID, NAVIO_PERDIDO_ROOM_B1F_PROMPT,
  NAVIO_PERDIDO_ROOMS2_1F_PRESET_ID, NAVIO_PERDIDO_ROOMS2_1F_PROMPT,
  NAVIO_PERDIDO_ROOMS2_B1F_PRESET_ID, NAVIO_PERDIDO_ROOMS2_B1F_PROMPT,
  NAVIO_PERDIDO_ROOMS_1F_PRESET_ID, NAVIO_PERDIDO_ROOMS_1F_PROMPT,
  NAVIO_PERDIDO_ROOMS_B1F_PRESET_ID, NAVIO_PERDIDO_ROOMS_B1F_PROMPT,
  NAVIO_PERDIDO_UNDERWATER1_PRESET_ID, NAVIO_PERDIDO_UNDERWATER1_PROMPT,
  NAVIO_PERDIDO_UNDERWATER2_PRESET_ID, NAVIO_PERDIDO_UNDERWATER2_PROMPT,
  navioPerdidoCaptainGuardFromAtlas,
  navioPerdidoCorridors1FGuardFromAtlas,
  navioPerdidoCorridorsB1FGuardFromAtlas,
  navioPerdidoDeckGuardFromAtlas,
  navioPerdidoHiddenCorridorsGuardFromAtlas,
  navioPerdidoHiddenRoomsGuardFromAtlas,
  navioPerdidoRoomB1FGuardFromAtlas,
  navioPerdidoRooms21FGuardFromAtlas,
  navioPerdidoRooms2B1FGuardFromAtlas,
  navioPerdidoRooms1FGuardFromAtlas,
  navioPerdidoRoomsB1FGuardFromAtlas,
  navioPerdidoUnderwater1GuardFromAtlas,
  navioPerdidoUnderwater2GuardFromAtlas,
} from "./navioPerdidoPresets";
import type { AraunaPresetCatalogEntry } from "./araunaPresetCatalog";

export const NAVIO_PERDIDO_CATALOG_ENTRIES: readonly AraunaPresetCatalogEntry[] = [
  { id: NAVIO_PERDIDO_DECK_PRESET_ID, label: "Navio Perdido · Convés", prompt: NAVIO_PERDIDO_DECK_PROMPT, guardFromAtlas: navioPerdidoDeckGuardFromAtlas },
  { id: NAVIO_PERDIDO_CORRIDORS_1F_PRESET_ID, label: "Navio Perdido · Corredores 1F", prompt: NAVIO_PERDIDO_CORRIDORS_1F_PROMPT, guardFromAtlas: navioPerdidoCorridors1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_ROOMS_1F_PRESET_ID, label: "Navio Perdido · Salas 1F", prompt: NAVIO_PERDIDO_ROOMS_1F_PROMPT, guardFromAtlas: navioPerdidoRooms1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_CORRIDORS_B1F_PRESET_ID, label: "Navio Perdido · Corredores B1F", prompt: NAVIO_PERDIDO_CORRIDORS_B1F_PROMPT, guardFromAtlas: navioPerdidoCorridorsB1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_ROOMS_B1F_PRESET_ID, label: "Navio Perdido · Salas B1F", prompt: NAVIO_PERDIDO_ROOMS_B1F_PROMPT, guardFromAtlas: navioPerdidoRoomsB1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_ROOMS2_B1F_PRESET_ID, label: "Navio Perdido · Salas B1F · Ala 2", prompt: NAVIO_PERDIDO_ROOMS2_B1F_PROMPT, guardFromAtlas: navioPerdidoRooms2B1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_UNDERWATER1_PRESET_ID, label: "Navio Perdido · Submerso 1", prompt: NAVIO_PERDIDO_UNDERWATER1_PROMPT, guardFromAtlas: navioPerdidoUnderwater1GuardFromAtlas },
  { id: NAVIO_PERDIDO_ROOM_B1F_PRESET_ID, label: "Navio Perdido · Sala B1F", prompt: NAVIO_PERDIDO_ROOM_B1F_PROMPT, guardFromAtlas: navioPerdidoRoomB1FGuardFromAtlas },
  { id: NAVIO_PERDIDO_ROOMS2_1F_PRESET_ID, label: "Navio Perdido · Salas 1F · Ala 2", prompt: NAVIO_PERDIDO_ROOMS2_1F_PROMPT, guardFromAtlas: navioPerdidoRooms21FGuardFromAtlas },
  { id: NAVIO_PERDIDO_CAPTAIN_PRESET_ID, label: "Navio Perdido · Escritório do Capitão", prompt: NAVIO_PERDIDO_CAPTAIN_PROMPT, guardFromAtlas: navioPerdidoCaptainGuardFromAtlas },
  { id: NAVIO_PERDIDO_UNDERWATER2_PRESET_ID, label: "Navio Perdido · Submerso 2", prompt: NAVIO_PERDIDO_UNDERWATER2_PROMPT, guardFromAtlas: navioPerdidoUnderwater2GuardFromAtlas },
  { id: NAVIO_PERDIDO_HIDDEN_CORRIDORS_PRESET_ID, label: "Navio Perdido · Piso Oculto · Corredores", prompt: NAVIO_PERDIDO_HIDDEN_CORRIDORS_PROMPT, guardFromAtlas: navioPerdidoHiddenCorridorsGuardFromAtlas },
  { id: NAVIO_PERDIDO_HIDDEN_ROOMS_PRESET_ID, label: "Navio Perdido · Piso Oculto · Salas", prompt: NAVIO_PERDIDO_HIDDEN_ROOMS_PROMPT, guardFromAtlas: navioPerdidoHiddenRoomsGuardFromAtlas },
] as const;
